apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: huginn-project
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: apps-huginn
      server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
    - "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: huginn-app
  namespace: argocd
spec:
  destination:
    namespace: apps-huginn
    server: https://kubernetes.default.svc
  project: huginn-project
  source:
    path: apps-huginn/
    repoURL: https://github.com/socrat3z/k3s-argocd.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
