apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: huginn-app
  namespace: argocd
spec:
  destination:
    namespace: apps-huginn
    server: https://kubernetes.default.svc
  project: sample-project
  source:
    path: apps-huginn/
    repoURL: https://github.com/kurtburak/argocd.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
